Adding Glassdoor Data
ccwoolfolk/ict-dev-wages pull request #8
Opened 2019-06-18 01:40 UTC by WSou

Glassdoor data is added to the project to provide additional information about Wichita software developer's salary. The data should be taken with a grain of salt since there is a little amount of data. Still, it does provide another insight into the developer salary. 

For full data please see the link below:
https://drive.google.com/file/d/1_Ox_UxgYD5NVaoTH6uF-mi2mZfmcT7TU/view?usp=sharing

2019-06-21 00:51 UTC, ccwoolfolk requested changes
Thanks for contributing, Top! I included some feedback because a) I had some and b) I thought it would be good to get some experience with receiving PR comments, making updates, etc. Let me know if you have any trouble with the process or questions about the feedback. You can respond directly in the conversation boxes below to make it easy for both of us to follow along. Responding by email is another option, but I find that approach difficult to follow unless the question is something very simple since you can't see the code being referenced.

Congrats on your first PR. :)

2019-06-21 00:51 UTC, ccwoolfolk commented on index.Rmd
> +[^2]: As a robustness check, the job category list was expanded to include an additional four categories. Wichita compared less favorably in this check. The mean annual salary was also within 2.5% of
This line is showing as changed, but I can't see any difference vs the original. Perhaps this is another line ending or file ending difference? Could you make them consistent?

2019-06-21 00:51 UTC, ccwoolfolk commented on index.Rmd
> +| $114,500 | $67,400 | $73,500 |
It might make sense to add another row here with the number of data points listed. My rationale is that since the high skills number is so low, it's probably best to make sure the reader understands that. You will want to add a row label for both the salary row and the "n" row. Here is a more thorough description of how to format tables in Markdown in case you have any questions: https://help.github.com/en/articles/organizing-information-with-tables

2019-06-21 00:51 UTC, ccwoolfolk commented on index.Rmd
> +### Does Wichita have a different mix of developer titles compared to peer cities?
I think this row and the space below it were a holdover from an old heading rather than something you intended to add.

2019-06-21 00:51 UTC, ccwoolfolk commented on index.Rmd
> +### Wichita employers' contribution to the job market
In Markdown, the number of `#` characters indicates the "level" of the heading. So this code:
```
# This is a top level heading meant for major sections
## And a smaller heading
### And smaller
#### And smaller still
```
yields this result:
# This is a top level heading meant for major sections
## And a smaller heading
### And smaller
#### And smaller still

I have been using 3 hashes (`###`) for sections. You can do the same, so `### Robustness check using Glassdoor data` or similar for your overall section. You can then use 4 `#`s for the subsections. I think this makes the most sense:
```
### Robustness check using Glassdoor data

#### Methodology
[text]

#### Results
[text]
```

2019-06-21 00:51 UTC, ccwoolfolk commented on index.Rmd
> +To be able to provide a sense of the context of how much an employer in Wichita contribute to the software community we need to obtain the salary information from employers around the Wichita area. T
This paragraph would be very important if the section had to stand on its own. We can probably cut it here, though, since the reader will have already seen the earlier sections describing the project goals and the roles included. Keeping those descriptions in one place also makes it easier to update if we ever want to change something (i.e., if we add "database administrator" to the list of jobs, we only have to change the text in one place and don't accidentally forget to change it here too).

2019-06-21 00:51 UTC, ccwoolfolk commented on index.Rmd
> +### Wichita employers' contribution to the job market
Also, do you want a byline in this section (might as well!)? You could put something like this:
```
### Robustness check...
> By Watthana Southivong
```
yielding this:
### Robustness check...
> By Watthana Southivong

2019-06-21 00:51 UTC, ccwoolfolk commented on index.Rmd
> +The data was collected through glassdoor.com. Glassdoor lets any employee and employer to anonymously post a review and work compensation about their company. The data that are collected through Glas
> The data was collected through glassdoor.com.

You can add a link like this: `[glassdoor](https://glassdoor.com)` which yields this: [glassdoor](https://glassdoor.com)

Also, the final sentence might make more sense as part of the next paragraph where you describe the time period used.

2019-06-21 00:51 UTC, ccwoolfolk commented on index.Rmd
> +The data is collected through searches for “software developer”, “web developer”, and “ computer programmer” with restriction to only Wichita, Kansas. Only compensation update that is from 2016 to 20
Same comment as above re: the job titles :)

2019-07-01 13:08 UTC, ccwoolfolk commented on index.Rmd
> +| $114,500 | $67,400 | $73,500 |
@WSou Is this the comment you had a question about? If so, I think you will want something like this:
```
||High skills|Low skills|Total Average|
|---|---|---|---|
| Salary | $114,500 | $67,400 | $73,500 |
| # data points | number goes here | number goes here | number goes here |
```
||High skills|Low skills|Total Average|
|---|---|---|---|
| Salary | $114,500 | $67,400 | $73,500 |
| # data points | number goes here | number goes here | number goes here |

2019-07-02 18:45 UTC, WSou commented on index.Rmd
> +### Does Wichita have a different mix of developer titles compared to peer cities?
Removed line

2019-07-02 18:47 UTC, WSou commented on index.Rmd
> +### Wichita employers' contribution to the job market
I do agree on the style that you provided. It's easier and simpler to understand. Will make the changes!

2019-07-02 18:52 UTC, WSou commented on index.Rmd
> +To be able to provide a sense of the context of how much an employer in Wichita contribute to the software community we need to obtain the salary information from employers around the Wichita area. T
Sounds Good :) Deleted the paragraph

2019-07-02 18:53 UTC, WSou commented on index.Rmd
> +The data is collected through searches for “software developer”, “web developer”, and “ computer programmer” with restriction to only Wichita, Kansas. Only compensation update that is from 2016 to 20
With the "respondent number that are being collected to Wichita Kansas Developer's Salary.xlsx" do you think it is best for me to provide a google drive link to the file instead?

2019-07-02 19:03 UTC, WSou commented on index.Rmd
> +The data was collected through glassdoor.com. Glassdoor lets any employee and employer to anonymously post a review and work compensation about their company. The data that are collected through Glas
Thank you! I thought that it may auto hyperlink it hehe.

2019-07-04 15:47 UTC, ccwoolfolk commented on index.Rmd
> +The data was collected through glassdoor.com. Glassdoor lets any employee and employer to anonymously post a review and work compensation about their company. The data that are collected through Glas
I never can remember if it is brackets first, then parentheses, or vice versa :)

2019-07-04 15:52 UTC, ccwoolfolk commented on index.Rmd
> +The data is collected through searches for “software developer”, “web developer”, and “ computer programmer” with restriction to only Wichita, Kansas. Only compensation update that is from 2016 to 20
Great idea!

2019-07-04 15:53 UTC, ccwoolfolk approved these changes

2019-07-04 16:00 UTC, ccwoolfolk commented
This looks great. After the google drive link you suggested, feel free to merge the PR (let me know if you don't have a "merge pull request" button; I'm actually not sure if you are able to merge directly now that I've marked the PR as approved.

2019-07-04 18:32 UTC, WSou commented
Made all the adjustments from the comments.

2019-07-04 18:37 UTC, WSou commented
I actually do not have a merge pull request button.

2019-07-04 22:55 UTC, merged